### ISSUE TITLE
Rocket.Chat keeps refreshing in the desktop app

### ISSUE THREAD

**Issue by wesleyg2005** [RocketChat/Rocket.Chat.Electron#1137]
## My Setup
- Operating System:
- App Version:
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

**Comment by ealley13** [comment]
I'm experiencing this same issue.

**Comment by lzrmihnea** [comment]
Same issue here, on VPN connection after latest update.

**Comment by puvanavia** [comment]
Same issue. What every channel I'm in or typing the desktop client will refresh and send me back to home often. 

We can't use Desktop version because of this bug. We have to go back to the channel we are chatting  and re-typing every time it refresh and it refresh too often.

Version 2.15.0
OS: Win10 x64
Installation type: Desktop client application

![image](https://user-images.githubusercontent.com/9207030/68357848-3dd79380-0149-11ea-9714-6ad1096f7c83.png)

**Comment by tassoevan** [comment]
It's fixed in the current version.
