### ISSUE TITLE
Rocket.Chat Electron Closes/Crashes after 10-15 seconds

### ISSUE THREAD

**Issue by analoghan** [RocketChat/Rocket.Chat.Electron#1173]
## My Setup
- Operating System: Windows 10 Pro - Build 10.0.17763 (Build 17763)
- App Version: 2.15.1
- Installation type: EXE

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Application completely closes after 10-15 seconds.   Has occurred on multiple users' systems in organization.

### Current Behavior
Application opens and functions normally.  Around 10-15 seconds, it simply closes with no apparent error message or warning.   Re-opening the application is successful for another 10-15 seconds, repeat ad nauseam.   Disabling antivirus and/or opening as Admin did not alter behavior.   A complete uninstall/reinstall did not alter behavior.   This problem began occurring after 3-4 weeks of normal behavior in the application and has occurred on multiple users' workstations running similar software loadouts.

### Expected Behavior
Application should not crash randomly.

**Comment by wreiske** [comment]
This may be related to #1152

**Comment by analoghan** [comment]
This issue was being caused by:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1152 - Crash if update check cannot contact GitHub server (2.15.1 regression)

Disabling auto-update functionality cleared problem.

**Comment by wreiske** [comment]
So after digging a bit, this issue is because of #1152. Our internet provider is having some issues talking to aws / github and it's causing the auto updates to crash several people's Rocket.Chat clients internally and on VPN.

We're still not able to push out the updates because the electron builds aren't signed!!!! 😡 
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1112

If we could push it out to all of our Windows machines with the `/S` (silent install) and `/disableAutoUpdates` flags we'd be golden... but we can't, because the builds aren't signed so Windows defender alerts.

@tassoevan any ETA on a fix for signed builds so we can push out the `disableAutoUpdates` to everyone?

**Comment by franckadil** [comment]
> This issue was being caused by:
> 
> #1152 - Crash if update check cannot contact GitHub server (2.15.1 regression)
> 
> Disabling auto-update functionality cleared problem.

Hi, How do you disable the auto-update ? I am pretty new to Electron and can't find a simple guide...
Thanks in advance for your help!

**Comment by HappyTobi** [comment]
Go to:
INSTDIR\resources\
Create „update.json“
Insert:
{
 “canUpdate“: false,
 “autoUpdate“ false 
}

See: https://github.com/RocketChat/Rocket.Chat.Electron/blob/develop/build/installer.nsh

**Comment by wreiske** [comment]
You can also disable auto update from the about rocket.chat menu. You just have to find it as soon as you start up rocket.chat, before it attempts to do an auto update check.

**Comment by franckadil** [comment]
Thanks @HappyTobi  I am just adding some precision here:

1. Edit the src/main/update.js file.
2. Apply @HappyTobi solution.
3. Arround row 176 comment this line:
`//app.once('start', () => ipcMain.emit('check-for-updates')); JungleWP We stop the updates.`

This is important for windows users to prevent the update check when you start your application.
Else it will crash everytime you open your app.

**Comment by franckadil** [comment]
> You can also disable auto update from the about rocket.chat menu. You just have to find it as soon as you start up rocket.chat, before it attempts to do an auto update check.

(Tested on Widows 10/7) The problem is that the newly building the app or launching the dev version, it crashes. Disabling the update check trough the code is the only solution so far until we get proper way to deal with the updates. 

By the way I would be happy if anyone can help me understand how to setup a git Public and Private based  Git update. All the guides out there are outdated, missing critical information and not beginner friendly at all...  

Have a good weekend guys !

**Comment by itmcg** [comment]
rocket.chat-desktopapp 2.17.7 don´t start on windows server 2016 as terminalserver, in RDP session. 
in local session it starts proper.
i installed rc with "change user /install" and autoupdate disabled.
in events shows "ntdll.dll" error
i´ve no idea why not working.
