### ISSUE TITLE
Can't download files with extension in Rocketchat Desktop client 2.15.3

### ISSUE THREAD

**Issue by layman48** [RocketChat/Rocket.Chat.Electron#1230]
Can't download files with extension in Rocketchat Desktop client 2.15.3
But in the browser downloads with the extension.
## My Setup
- Operating System: Windows 7
- App Version: 2.15.3
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by javac1225** [comment]
I may have the same problem in my environment.
Similar problems occur in the teammate's environment.

The environment is Windows7, 
but it also occurs in Windows10 environment. 

The version of Rocket.Chat is 0.74.3 
and the Apps Engine version is 1.4.0, built on docker.

This problem does not occur when using the browser directly, 
but only when using the "Rocket.Chat Desktop Client".

If I try to download a file uploaded to Rocket.Chat, 
a file dialog will be displayed, but pressing the Save button 
will close the dialog but the file will not be saved.

Checking with Fidder 4, a 403 request was returned 
in the download request when the problem occurred.
(GET request to the URL /file-upload/..)

Even in this state, reading and writing messages in chat 
has been done without problems.

We also know that this issue can be temporarily resolved 
if you "Reload with ignoring cache".
However, it will not be a real solution 
because it will be reproduced again over time.

I know how to reload, but because it is used in a community 
that many users use, it may have affected Rocket.Chat's 
reputation.

All the other features of Rocket.Chat are great.
Thank you for solving it.

**Comment by layman48** [comment]
It is necessary to allow display of extensions for registered file types in Windows.

**Comment by 1JesusOrtegadelCastillo** [comment]
@layman48  How can I allow that?
