### ISSUE TITLE
Auto-Away on Windows 10 does not follow user's machine activity

### ISSUE THREAD

**Issue by ChristineBoersen** [RocketChat/Rocket.Chat.Electron#1260]
## My Setup
- Operating System: Windows 10 (1709, 1803, and 1809)
- App Version: 2.15.3
- Installation type: exe built from source

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
The Auto-Away functionality seems to only work when the Rocket.Chat.Electron app is in focus (vs minimized or just task tray)

### Current Behavior
Auto-Away goes to Away after the set 300 seconds when the user is still using their computer (keyboard/mouse activity)

### Expected Behavior
Auto-Away should track based on keyboard/mouse activity of the logged in user, irrespective of the minimized/maximized/taskbar state of the Rocket.Chat.Electron application

I did look at the source for 2.15.3, and the source library used for this detection on windows, and it is using the method recommended from microsoft.. Wondering if that thread is somehow getting suspended when Chromium/electron isn't in the foreground?

**Comment by detoxhby** [comment]
This is an extremely annoying bug in enterprise enviroments where 99% of users depend on whether they can reach a person or not based on their status at the moment.

This is an ongoing issue till 15.1 released which was **3+ months ago**. Couple of organizations are thinking about dropping Rocket.Chat completely just because this issue is not solved. I really hope the developers realize that business use-case is NOT about letting the browser run in the background for the chat.

Thanks in advance.

**Comment by ChristineBoersen** [comment]
Well hopefully they will grab the PR I submitted (or suggest what they don't like) as it helps solve it. 
I also have a PR I'm about to do for the server side to help show how long a non "online" user has been in that status as lots of managers/bosses use that to get an idea what their employees are doing...

Again, another business use case that is a priority for adoption in my environment.

**Comment by detoxhby** [comment]
Still nothing? I can't believe it... what happened with the developers?
