### ISSUE TITLE
Unread Message Counter

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat.Electron#1330]
My Setup
Operating System: Windows
App Version: 2.15.5
Installation type: dmg
 I have tested with the latest version
 I can simulate the issue easily
Description
When private messages arrive on the taskbar, the application icon flashes (unread messages). Is there any way to make so that instead of blinking there is a counter of unread messages? 1,2,3 etc.

**Comment by CitizenDev** [comment]
Weird thing is that they seem to already have the icons for it /src/public/images/tray/
But for some reason unused. And it think the reason is it is unreliable.

Many versions back i made a fork and got my custom counter icons working, but they frequently lie. So my logic is they opted to use just the dot to show  you have unread messages, but just not how many.

Would be nice if dev would elaborate on this.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
