### ISSUE TITLE
RocketChat frequently doesn't appear on startup

### ISSUE THREAD

**Issue by wizofaus** [RocketChat/Rocket.Chat.Electron#1334]
Basically an existing bug which is supposedly already fixed: https://github.com/RocketChat/Rocket.Chat.Electron/issues/851

But it happens very frequently for me and when it does I need to force-kill any Rocket.Chat.exe processes, and edit window-state-main.json file to set isHidden to false.

Running v2.15.5.

**Comment by dfaure-kdab** [comment]
Same here. Windows 10. Very annoying. Why does this JSON file even support isHidden:true in the first place? How useful is an application that supposedly starts but does not show any window (nor have a system-tray icon)?

**Comment by dfaure-kdab** [comment]
Actually, it does have a system-tray icon. So there is a much simpler workaround than killing and editing a json file: opening the system-tray overflow icon (arrow up), and clicking on the (gray) rocket chat icon.

It's still a bug (since I close the application with the window **shown**, not hidden) but at least the workaround is much easier.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
