### ISSUE TITLE
'New Update is Available' and then 'You will be notified when it is ready'

### ISSUE THREAD

**Issue by WardeWynter** [RocketChat/Rocket.Chat.Electron#1428]
## My Setup
Windows 10

![image](https://user-images.githubusercontent.com/48665223/70183489-ffc69300-1739-11ea-9b10-e02ab60b05c3.png)

### Current Behavior
Usually, I get the message as per the screen image...I get asked to upgrade to the latest version, and then get a message letting me know it will be updated when it is ready?

### Expected Behavior
should just update

**Comment by TulkasGer** [comment]
Same as Ticket 1300 I Think:
[https://github.com/RocketChat/Rocket.Chat.Electron/issues/1300](url)

**Comment by johnyb0y** [comment]
Look at the top of the notification box. “Downloading Update”. 
This message tells you that the update will now be downloaded in the background and you will be notified when “it is ready to be installed”. 
Shortly after that the installer opens. 
Also this notification box isn’t new and has been part of the update process since forever.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
