### ISSUE TITLE
Rocket chat 2.15.0 - View for Updates not work

### ISSUE THREAD

**Issue by regorodrijl** [RocketChat/Rocket.Chat.Electron#1440]
## My Setup
- Operating System: WIndows 10 pro
- App Version: 2.15.0
- Installation type:  exe

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description
The bug is related to the Rocket.Chat Desktop app.

![image](https://user-images.githubusercontent.com/15713779/70692244-2f861580-1cbb-11ea-8eed-6b8215023093.png)

In this view, the blue "INSTALL UPDATE" button doesn't work.

### Current Behavior
The button not work.

### Expected Behavior
The buttom will update my version.

**Comment by HeadWrench** [comment]
"Doesn't work"  - meaning that the update doesn't proceed.
The Install button dismisses the window, and displays a confirmation that I'll be notified when the update is ready to be installed. But no notification is delivered - apparently the update hasn't been downloaded, because I keep getting the same "Update Available" notice.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
