### ISSUE TITLE
App icon is invisible in System tray on windows10

### ISSUE THREAD

**Issue by SamvegJain** [RocketChat/Rocket.Chat.Electron#1476]
## My Setup
- Operating System: Microsoft Windows 10
- App Version: 2.15.5 (Fix is not available in latest version 2.17.2 as well)
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
- On windows 10 Electron app icon is invisible in system tray 
- Once the Electron App is launched, the app shows up only in "System Tray" and that icon is invisible. Then after clicking the invisible icon from system tray app launches. Ideally when the app is launched it should show up in Task Bar instead of just showing in System tray.

### Current Behavior
Electron app icon is invisible in system tray. 
On launched the application from start menu app is going to System Tray. After clicking the link from system tray app is getting launched.

### Expected Behavior
Electron app icon should be visible in system tray.
On launching the app, app should directly launched and it should displayed in Task bar.

**Comment by ankar84** [comment]
Rocket.Chat icon **is visible** in system tray. 
But by default in Windows 10 RC system tray icon appears in **top system tray area**, that available by clicking **up arrow**:
![image](https://user-images.githubusercontent.com/4023037/73042768-7bf47180-3e73-11ea-994d-b3d818309396.png)
User can **drag and drop** RC icon to **main system tray**:
![image](https://user-images.githubusercontent.com/4023037/73042807-a0e8e480-3e73-11ea-9ca7-f66cc88b63ce.png)
But I agree, that it is a little tricky for our users. 
- They double click RC desktop icon, RC launches. 
- Then they close it pressing right corner cross. 
- RC not closing, but minimized to system tray (often to top area) and users do not see RC and try to double click desktop icon again and again and nothing happens (because RC is already launched). 

We had a lot help desk tickets about that case.
But I don't know the right way to fix that problem.

**Comment by tassoevan** [comment]
@ankar84 
> try to double click desktop icon again and again and nothing happens (because RC is already launched)
I've expected this to be fixed in the latest release. Is it still happening?

**Comment by tassoevan** [comment]
Suggested workaround: to display a balloon when the window is minimized to the tray.

**Comment by ankar84** [comment]
> I've expected this to be fixed in the latest release. Is it still happening?

Yes, 2.17.5 maximizes on desktop icon double click. That very good for us and will solve a lot of user problems.
Thanks a lot for that!
