### ISSUE TITLE
7294 segmentation fault (core dumped) on startup on Arch

### ISSUE THREAD

**Issue by nilsnolde** [RocketChat/Rocket.Chat.Electron#1540]
## My Setup

- Operating System: Manjaro Linux
- App Version: 2.17.7-2
- Installation type:  Arch Linux AUR [rocketchat-desktop](https://aur.archlinux.org/packages/rocketchat-desktop/) package

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

After the lastest system upgrade, the AUR packaged [rocketchat-desktop](https://aur.archlinux.org/packages/rocketchat-desktop/) stopped working and throws a `segmentation fault (core dumped)`. #802 is similar, but I'm not sure how to verify which library breaks rocket.chat. I thought maybe I first test the waters, see if someone else has more knowledge/experience. If not, I'll try the downgrade of `glibc`

### Current Behavior

Segmentation fault on client startup.

### Expected Behavior

Client should open without faulting.

**Comment by nilsnolde** [comment]
Hmpf, sorry.. I just realized there's another AUR package out there, which seems to be more accepted: https://aur.archlinux.org/packages/rocketchat-client-bin/. I went with that one and it worked just fine without downgrading anything.

**Comment by ml-** [comment]
@nilsnolde The segfaul is caused by old configs. There is a AUR comment about that.
But you should use `rocketchat-client-bin` anyway if you don't care about building from source. RocketChat has a brocken tray with Electron 8 right now and Electron 7 is not in the official repositories.

I will figure something out for the `rocketchat-desktop` package if upstream won't switch to Electron 8 in near future.

Sorry for the inconvenience.
