### ISSUE TITLE
Upgrading to the latest Stable Electron Version

### ISSUE THREAD

**Issue by Somtozech** [RocketChat/Rocket.Chat.Electron#1543]
This might solve some crash/incompatibility issues.

**Comment by ml-** [comment]
I tried delivering Rocket.Chat with electorn 8 on Arch. It has issues with previous user data in `$XDG_CONFIG_HOME` but all files are recreated properly if you remove existing configs. Obviously, user configurations have to be redone.

Electron 8 breaks closing to tray, or rather "Tray Icon" in general.

**Comment by idarlund** [comment]
Jitsi has just rolled out end-to-end encrypted video conference; https://jitsi.org/blog/e2ee/
This requires Chromium 83 because it uses the new chromium WebRTC API called "Insertable Streams".

Electron 9 has hit stable last week with chromium 83.

Please upgrade Rocket Chat Electron client to electron 9 so that we can use jitsi with end to end encryption.

**Comment by idarlund** [comment]
Newest stable electron is now 9.0.4. When will rocket.chat be upgraded to this version?

**Comment by idarlund** [comment]
Got an answer in the #support chat on rocket.chat:
"They'll take care of this ASAP!"
To see the message and the thread, please check it out here:
https://open.rocket.chat/channel/support?msg=6CfHcjMdrahyH2o6m

**Comment by idarlund** [comment]
Thanks a lot for a new updated electron version (https://github.com/RocketChat/Rocket.Chat.Electron/blob/master/package.json#L90).
This issue should be closed.
