### ISSUE TITLE
Using 100% cpu resources

### ISSUE THREAD

**Issue by bartosz-kepka** [RocketChat/Rocket.Chat.Electron#1656]
## My Setup

- Operating System: Ubuntu 20.04
- App Version: 2.17.10
- Installation type: Ubuntu Software Center

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

Using all cpu resources from time to time for ~30 sec.
During 100 working hours happened 4 times.

**Comment by mmgoilf** [comment]
I have the same issue on Debian 10, it uses 100% of one core every 2 seconds or so. On my laptop it is especially noticeable since my laptop gets hot. I am using snap for rocketchat. Interestingly, on arch linux I do not have this problem. On arch I got rocketchat from the AUR, but it was the same version, 2.17.10. Maybe it is a issue with snap?

**Comment by mmgoilf** [comment]
2.17.11 has this issue as well

**Comment by engelgabriel** [comment]
What version this started to happen?

**Comment by tassoevan** [comment]
I guess it's something wrong with the Snap package. I'll take a look ASAP.

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
