### ISSUE TITLE
Tabs per channel/room

### ISSUE THREAD

**Issue by rhysxevans** [RocketChat/Rocket.Chat.Electron#166]
## My Setup
- Windows 10 and 2012R2: 
- Current App: 1.3.1: 
## Description

Hi

We would like the ability to have multiple tabs within the app. Each tab would essentially be a channel/room. and each tab would "alert" separately. Ie if the update comes from channel X and we have channel Y and Z open as well the tab hosting channel X should flash/have an update icon.

Thanks
##

**Comment by engelgabriel** [comment]
Thanks for the suggestion @rhysxevans but unfortunately this is too specific for your use case. We have not received anyone else requesting such a feature so we can't afford to spend time building this. If you develop a this feature yourself, please submit a PR and I'll be happy to review and merge it. Cheers, Gab.

**Comment by mikhey** [comment]
I was about to post a new issue when I came upon this.  This would be a nice feature to have.  I could see it as an optional feature though.  I was looking for some way to switch between conversations quickly rather than to have to use the search or scroll through the long list of people/channels to chat with.  If I'm already chatting thing them I'd like to use <kbd>Ctrl+Tab</kbd> & <kbd>Ctrl+Shift+Tab</kbd> to navigate through the tabs like in a browser.  Conversation switching between channels and individuals can be somewhat of a pain at times and it would be nice to be able to just use the keyboard to navigate to them.  

I could see how tabs may be much, but maybe if I hold <kdb>Ctrl+Tab</kdb> it could show a list of recent conversations and allow me to navigate through it by consecutively pressing <kbd>Tab</kbd> or <kdb>Shift+Tab</kdb> - like the dialog in Visual Studio and VS Code to switch between different active documents.
