### ISSUE TITLE
Making the Icon Tray notify different situations

### ISSUE THREAD

**Issue by JonathanNasc** [RocketChat/Rocket.Chat.Electron#172]
## My Setup
- **My OS name and version**: Ubuntu 14.04
- **My current app version**: 1.2.0
- [ ] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

I propose three different types of icons:
1 - (...) Normal - the current icon of Rocket
2 - (!) Notification - for new messages in general (configurable)
3 - (@) Important notifications - for mentions and direct messages (configurable)
#### Current Behavior

If somebody say something in a channel, the only notification is a desktop pop-up. But not always I repair this pop-ups and if nobody mention me or send me a direct message I don't see this new message quickly.
I never try Rocket Chat desktop for the other platforms, maybe this problem is exclusive of Ubuntu. 
#### Expected Behavior

I want to configure channels to notify me with pop-up and a exclamation (!) icon tray. When someone mention me or send me a direct message a more important icon tray will tell me it.

Please let's discuss about it
##

**Comment by ohaessler** [comment]
I would also love to have a visual notification on the Icon. I am using Gnome 3.14 on Red Hat Enterprise Linux and the desktop notification only stays for a few seconds and than disappears to the notification area which is not visible al the time. A icon notification would solve that issue.

**Comment by berthermans** [comment]
Yes please make this configurable. It's currently the only reason not to move completely to Rocket Chat.

**Comment by dckc** [comment]
Indeed, this is a big regression w.r.t. using a web browser. In the web browser, (a) the title reflects the chat service, not "Rocket.Chat" and (b) when there's a pending message, the title changes.

**Comment by Babeetlebum** [comment]
Related to #68 ? Our userbase is insisting on this and it is preventing us from making the change to Rocket Chat

**Comment by windsource** [comment]
In skype for business / Windows 7 the icon changes when new messages arrive. That's usually what you recognize when coming back to your PC after a while. Would be very nice to have this in Rocket-chat as well.

**Comment by dark-penguin** [comment]
I have confirmed that on Windows, the Rocket.Chat tray icon changes to red, and also displays the number of unread messages, which is perfect. So this issue is Linux-specific.

Also, it would be much better if the default tray icon was blue, like on Windows, because some of us use a light desktop manager theme, and the current white-on-gray icon is barely visible. Not as bad as Mattermost or Steam, of course, but not nearly close to what Windows users get.

**Comment by windsource** [comment]
In the browser I see the icon changing its color and showing the number of unread messages. But the tray icon of the Windows Desktop app does not change its color and does not show the number of unread messages. I am using Windows 7 and Rocket.Chat+ Version 2.4.0. Sever version 0.53.0.

**Comment by windsource** [comment]
Works with version 2.5.0 of the Windows desktop app.

**Comment by mybigfriendjo** [comment]
Would also love if there was an option to make the taskbar (not the TrayIcon) blink on configurable events like direct mentiones and private messages. For the installed Application this would ofc only happen when it's actually open. If it's closed the TrayIcon blinking would be nice.

Just a change of color of the Icon can sometimes be too subtle to recognize right away.

**Comment by Anguel** [comment]
+1 for this request: I did some research and it looks like notification duration can be only controlled through Windows registry, i.e. not by applications directly, and can be set only to up to 5 minutes. In order to prevent chat messages from being overlooked (which happens constantly because users not always sitting in front of their PC just don't see the small number in the tray) the only possibility I can think of is to make the Rocket Chat client blink in the **taskbar** (and optionally in the tray), even when minimized to the tray. Blinking the tray only is also not clearly visible.

**Comment by andranikvfx** [comment]
+1 for this. We are running into an issue where people just miss messages or don't see it for a while. Another option could be to bring the rocketchat window in front of everything to indicate that there is a new message.

**Comment by Maqsyo** [comment]
@andranikvfx we are missing exactly this feature

**Comment by e11bits** [comment]
This feature would be very helpful.

**Comment by shinebayar-g** [comment]
Just installed Rocketchat desktop and surprised that there is no application settings at all. How do I get notified if someone write in channel or write DM to me? :scream:

**Comment by dark-penguin** [comment]
Is it possible to configure the tray icon to only react to mentions? Ideally, optionally change color on all unread messages, but only display the notification dot on mentions.
