### ISSUE TITLE
Do not post a new release with thousand of new critical errors 

### ISSUE THREAD

**Issue by mountstone** [RocketChat/Rocket.Chat.Electron#1778]
It isn't hard to use v3.0.0-alpha/beta naming convention or sth, because every version you use seems to be treated as stable but it's not. You are pronuncing new version but it's just a pandora's box. 

Consider to add more info in every version, e.g. wasn't tested well...

There are lot of companies which use open source msng tools, one of them is Rocket Chat, but there is no place to release software in that way just because it's open source and you don't take responsibility for it.

**Comment by ankar84** [comment]
Partly I agree with @mountstone 
3.0.0 should be some alpha version for enthusiasts only and for wide users amount should be available 3.0.2 of some stable one
@tassoevan we need alpha channel

**Comment by tassoevan** [comment]
First of all, I want to let clear that I'm not going to make any excuses on how clunky and unprofessional my maintenance has been, specially after the "MacOS Catalina battle" and three months of development freeze due to a code signing certificate renewal nightmare. The following examples just illustrate why things happened the way they happened.

@ggazzo and I have agreed on not only making alpha releases as well doing some sort of dogfooding (we do it a lot for RC server).

The major blocker for it is our tooling: it's not hard to find comments from me in this repo talking about how unstable Electron API and `electron-builder` are. In fact, most of the rewrite for 3.x was made to address long-standing security issues coming from bad practices required by the framework in the near past. For instance, the current "invalid server" errors are result of our first attempt to match the client and the server without giving room for malicious instances abusing the preload script.

On the topic of building the app, [a bug in `electron-builder` deployment to GitHub](https://github.com/electron-userland/electron-builder/issues/4940#issuecomment-698738497) made us lose a day of work. Despite [alpha and beta channels being available](https://www.electron.build/tutorials/release-using-channels), it forces us to completely abandon the standard git-flow, merging everything in the `master` branch and tagging stable commits* - and we're already going for it. Ironically, our expectation is to release more often, almost continuously, under this workflow.

* This is happening in our [Fuselage monorepo](https://github.com/RocketChat/Rocket.Chat.Fuselage) too because Lerna isn't compliant to git-flow.

**Comment by gniezen** [comment]
@tassoevan Would you mind elaborating a bit on your workaround for the `electron-builder` "socket hang up" bug?
