### ISSUE TITLE
Packaging instructions out of date

### ISSUE THREAD

**Issue by llama233** [RocketChat/Rocket.Chat.Electron#1780]
Hi there,

I have for the last year or so created my own deb package for use on Raspberry Pi desktops (armv7l). As of version 3.x.x I can no longer run "yarn release" to build a deb as described in the README.md (yarn returns "error Command "release" not found."). What is the current "proper" way to create a deb package? From picking through various issues I've tried the following:

```
yarn install
yarn build
yarn electron-builder --armv7l --linux deb
```

This results in a deb, but when installed I get "Error: cannot find module 'chokidar'" when trying to start rocketchat-desktop. I've tried installing chokidar ("yarn add chokidar") and also removed the yarn.lock and rebuilt but it always results in that missing module. What am I doing wrong here?

Cheers,
Andrew

**Comment by Sx3** [comment]
error Command "release" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

when try to use the command
**yarn release** 

on windows

**Comment by VasiliyMooduckovich** [comment]
packagin for windows target out of date as well:

`• packaging       platform=win32 arch=x64 electron=10.1.3 appOutDir=dist/win-unpacked
  ⨯ Application entry file "app/main.js" in the "/home/odmin/softbuild/Rocket.Chat.Electron/dist/win-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.`

just guessing - `main.js `doesnt exist anymore since it been rewriten on typescript and now it's called `main.ts`

[https://github.com/RocketChat/Rocket.Chat.Electron/commit/00435e1930d7f032c58334877f3af1b0b47f74fa](url)

**Comment by jeanfbrito** [comment]
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!
