### ISSUE TITLE
Topsteptrader failure of dedicated ap to update

### ISSUE THREAD

**Issue by cmasem** [RocketChat/Rocket.Chat.Electron#1865]
## My Setup

- Operating System: Windows 10
- App Version: 2.17.11
- Installation type:  don't remember

- [ ] I have tested with the latest version
- [ x] I can simulate the issue easily

### Current Behavior
Every time I open the app I'm prompted to update but it doesn't respond to the update after downloading. Prompt indicates I'll be prompted to update the next time I open the app

**Comment by Maqsyo** [comment]
Duplicate from #1837 #1670 #1205 and so on

Click on "Skip this version" or download the newest version from here:
https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by homberger** [comment]
This issue alone makes it impossible to convince a company that Rocket.Chat is a professional software that could replace Slack or MS Teams. It's a shame. Rocket.Chat had so much potential. Had. Most of the interested companies choosed other solutions because of those stupid bugs that keep existing over years.

**Comment by ankar84** [comment]
Closing in favor of #1670
