### ISSUE TITLE
UI issue in macOS - Red notifications on a red icon

### ISSUE THREAD

**Issue by moroniflores** [RocketChat/Rocket.Chat.Electron#1937]
## My Setup

- Operating System: macOS Big Sur 11.1
- App Version: 3.1.1
- Installation type: dmg from https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.1.1

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
Since the changes in the Dock icon, notifications are easy to ignore as they are a red over red.
![image](https://user-images.githubusercontent.com/4323309/103516733-47ee4280-4e71-11eb-8a5d-215e90aa267c.png)

### Expected Behavior
The Dock icon should not be the same or very similar colour shade as system notification icons.

**Comment by mpachkov** [comment]
I totally support this request. Red on red is awful .

**Comment by andylin2004** [comment]
Seconded. However, #1941 should mitigate the issue as the icon should be shrunk down to proper scale (like how notification badges show up on iOS)

**Comment by maiksd** [comment]
Second this too. I also don't think, resizing the icon migitates this issue enough. If the dock is small enough (necessity on small screens or with many applications in it), the badge will still not be visible, which is quite a problem with a chat application.

**Comment by cazetto** [comment]
For me it's appearing as in the image below:
<img width="138" alt="Screen Shot 2021-08-20 at 16 20 08" src="https://user-images.githubusercontent.com/230598/130283804-c1ce11fc-5e73-4310-83f2-75a71159497c.png">

 Closing it since it appears to be fixed here: https://github.com/RocketChat/Rocket.Chat.Electron/pull/1941. If you have any problems related, please reopen it.
