### ISSUE TITLE
Improve away detection

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Electron#194]
If the screen goes blank or laptop lid shut, etc we should be setting the user to away.
##

**Comment by OrdinaryGuy** [comment]
I have to add that the application changes to active only when user focusing it.
And i guess it would be good tone to react on lock workstation, screen sleep, system sleep, hibernate, timeout and then all the way back - unlock, wake up, wake up, wake up, user activity.

**Comment by gdelavald** [comment]
This could be achieved with [power-monitor api](https://github.com/electron/electron/blob/master/docs/api/power-monitor.md) provided on electron.

**Comment by josecanciani** [comment]
There are several opened issues in the server side regarding away and notifications:
    https://github.com/RocketChat/Rocket.Chat/issues/3667
    https://github.com/RocketChat/Rocket.Chat/issues/1602
    https://github.com/RocketChat/Rocket.Chat/issues/7130
Apparently, even if you set your desktop client to Away manually, the server will not send you push notifications for 5 minutes. If you leave your desk, you cannot know if someone message you in those five minutes unless you open the app in the phone.

One solution would be if we just logout :) But that is not practical as you need to login again by typing the password. I wonder why is there not an offline option? But even if there is a way, there is no way to fix this automatically. Do anyone know if there is a way to send commands via a CLI? One could add an OS trigger to set the client offline/logout when computer is locked, for example.

Sorry, I may be a bit offtopic, but since I've had some important messages missed in just a week using this app, I'm a bit concerned about it :)

Jose

**Comment by btorellALTA** [comment]
Does anybody know what the status of this issue is? It would definitely be nice if the app would mark users as Away when they lock their computers instead of having to close the app or log off.
