### ISSUE TITLE
Add server address to .msi package

### ISSUE THREAD

**Issue by ozzyBLR** [RocketChat/Rocket.Chat.Electron#1988]
My Setup:
- Operating System: Windows 10 20H2
- App Version: rocketchat-setup-3.1.1.msi
- Installation type: run .msi via GPO
In our organization we are planning to deploy Rocket.Chat via GPO. For now I can't find a way to add server address to .msi package for the user to be prompted to type in login/password only during the first launch. I used Orca to review .msi with no result.
Is there any way to add server address? Directly to .msi or starting .msi via CLI with additional parameters.

**Comment by TazerReloaded** [comment]
Our solution is to deploy a basic config.json to AppData, missing sections are automatically added on first start. While that's not the most convenient solution, it works for now. I would like to have a few installer options too!

**Comment by geoffritter** [comment]
This is unlikely to be fixed any time soon unless electron-builder provides the option to do this.  This is a limitation of the way electron-builder uses wix... Unless there is a way to use the "additionalWixArgs" parameter in electron-builder.json to write properties supplied to the MSI to an ini file.  But if you are using GPO software deployment, you would have to customize a transform file anyway to apply the property.  So all this gets you is a minor convenience over the workarounds listed above.

Much easier to set "perMachine" in the electron-builder.json's MSI section so that the MSI file gets installed system wide by default.  This is a reasonable default for an MSI since the consumer of MSIs are organizations hosting their own server.  With that setting, all you would have to do is deploy a servers.json and update.json file to the expected install directory.

Personally, rocketchat could benefit from a full enterprise customization option that does things like hide the developer tools, removes the server list and menu options for selecting the server and a few other things to lock the app down to just one enterprise.

See:
https://github.com/electron-userland/electron-builder/blob/4a5132f25f64e1d0907e77e6fc309edf01d1b04b/packages/app-builder-lib/src/options/MsiOptions.ts
https://github.com/electron-userland/electron-builder/blob/28cb86bdcb6dd0b10e75a69ccd34ece6cca1d204/packages/app-builder-lib/templates/msi/template.xml
https://stackoverflow.com/questions/55460379/how-to-parameterize-msi-file-from-electron-builder

Electron builder has its own set of MSI Properties it defines in the template that are controlled by options passed to the config file.   If there is a solution as-is it might be with "additionalWixArgs"  Assuming the command line api is powerfull enough to configure setting INI file lines as explained in the stackoverflow article.  Some minor changes to the import of servers.json and update.json files could accommodate that as ini files should be trivial to import.

**Comment by jeanfbrito** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron#default-servers
