### ISSUE TITLE
Unable to provide a custom port when connecting to a URL

### ISSUE THREAD

**Issue by wagoodman** [RocketChat/Rocket.Chat.Electron#45]
At launch when entering a URL to connect to, entering ":<port>" results in an immediate "Not a valid instance url" message. It appears that no attempt was made to connect. This means that any rocket.chat installations with a custom port number (other than 3000) will not be able to use this gui.

**Comment by codecat-** [comment]
Hello. Basicaly if you used instructions from oficial guide, you can see that installation with custom 3000 ports is used to install server application behind nginx/apache(mode_proxy). If you want to host it withoud any web server, you can specify 80 port instead of 3000 and server will listen specified socket.

**Comment by wagoodman** [comment]
Correct. How do I connect this GUI when the Rocket.Chat server port is on port 4000 instead of the standard 3000 or 80?

**Comment by rodrigok** [comment]
This should be fixed
