### ISSUE TITLE
Feature request: Tray icon should blink if new PM received

### ISSUE THREAD

**Issue by johntq** [RocketChat/Rocket.Chat.Electron#452]
## My Setup

 - __My OS name and version__: Windows 7 64.bit
 - __My current app version__: 2.8.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

If you receive a PM, the tray icon is changed to red icon with an unread number indicator.

#### Expected Behavior

It would be helpful, that in case of new PM the tray icon is blinking. Either as default or as option.

**Comment by alexbrazier** [comment]
I tested this on Windows 7, and it seems to work as expected, unless you are talking about something else?
Do you have any settings enabled to disable notifications for direct messages?


![image](https://cloud.githubusercontent.com/assets/5689874/26287417/fb3eebea-3e72-11e7-8c02-c5a5f6a24ca3.png)

**Comment by johntq** [comment]
You talk about the app Icon. I mean the tray icon. In our installation, many people overlook a new PM.
![image](https://cloud.githubusercontent.com/assets/28802313/26295462/51a77b76-3eca-11e7-87da-69b36703a60b.png)

**Comment by alexbrazier** [comment]
@johntq I don't think its possible to make the tray icon blink on windows. We could potentially change the colour if that would help?

**Comment by johntq** [comment]
Hmm. Another idea: It is possible to have an option wich can set the tool tip timout to endless or open the main window in case of new PM?

**Comment by Zerocool56** [comment]
Why you cant make the icon blink?

If you can change image - you can "blink"

Just change images

**Comment by johntq** [comment]
I will explain the motivation behind my request.

Our company is evaluating the transition from Jabber protocol based client to Rocket.Chat.

Now we are in the testing phase. Many participant have reported, that noone notice a new PM. Some percent of our Instant Messaging are real time information, such as _come over_ or _pizza is arrived_. Meanwhile, some have starved to death because they have not noticed their PM. 

For us it is very important that you can notice new PM better.

**Comment by dbenz04** [comment]
I have a similar issue/feature request. We have users also missing PMs because they miss the few seconds that the pop-up notification appears. Ideally, I would like it if the pop-up notification of a new message stays on the screen until clicked or dismissed. I have seen this with other IM clients, do you think this would be possible to add to Rocket.Chat?

**Comment by vcapretz** [comment]
isn't the same issue as https://github.com/RocketChat/Rocket.Chat.Electron/issues/487? If so, we can close one of them! 

@geekgonecrazy

**Comment by johntq** [comment]
It looks like the same. Important: I am talking about the tray icon, not the task bar icon.

**Comment by vcapretz** [comment]
sure! the other issue is also about the tray icon :smile:

**Comment by AphoticGig** [comment]
I'm in the process of reviewing your app for our organization.  Having the Tray Icon blink when a message arrives is a key feature for our member experience.  leaving the app open on the task bar is not an option for us at this time.   Am I correct that no one is working on this feature or am I missing the setting in preferences?

**Comment by kayahr** [comment]
I made a very simple change to implement a blinking tray icon:

https://github.com/RocketChat/Rocket.Chat.Electron/compare/develop...iplabs:feature/blinking-tray-icon

When an alert tray icon is to be displayed then it blinks (Toggling between normal tray icon and the requested alert tray icon every 500ms). When a non-alert tray icon (normal or unread) is displayed then it does not blink.

Works pretty well here but I'm not sure if it is ready for a pull request yet, because there are some open questions:

* Is it ok to hardcode the blinking because everyone will benefit from it? Or is it better to make it configurable?
* If it must be configurable then what is the correct place for the new config? Server-side like the "Unread Tray Icon Alert" config? Or client-side like the "Toggle Menu Bar" setting?
* I only changed the behaviour for Windows/Linux but what about OSX? Do Mac users need a blinking icon? Or is the OSX-builtin message counter on the app icon already notifying enough?

If you want to try the blinking without compiling your own client then you can locate the `app.asar` file in your Rocket.Chat installation, unpack it somewhere, patch the unpacked content with [blink.diff.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/1942067/blink.diff.txt), repack the asar file and replace the original one with it.

**Comment by marcosmolinamaxicon** [comment]
When you click the close button on the windows bar after that icon does not turn orange.

![image](https://user-images.githubusercontent.com/39923299/58124234-211fc180-7be4-11e9-9d6b-7d967792bf1d.png)

but, when click em close button of program 
![image](https://user-images.githubusercontent.com/39923299/58124291-47456180-7be4-11e9-8819-8104a5c717b3.png)

![image](https://user-images.githubusercontent.com/39923299/58124343-63490300-7be4-11e9-96d3-c2a931f4e9d2.png)

**Comment by grantdowco** [comment]
> If you want to try the blinking without compiling your own client then you can locate the `app.asar` file in your Rocket.Chat installation, unpack it somewhere, patch the unpacked content with [blink.diff.txt](https://github.com/RocketChat/Rocket.Chat.Electron/files/1942067/blink.diff.txt), repack the asar file and replace the original one with it.

Seems like this patch no longer works with the current Rocket.Chat 2.15.3 as the code looks like it's been refactored at some point.   Did you ever update your patch for this latest version?

**Comment by baiking** [comment]
![rc_blink](https://user-images.githubusercontent.com/27258511/106112279-03ac4480-6188-11eb-9bdf-fc1413709885.gif)
this should be must have feature!!

**Comment by manavagr1108** [comment]
I was trying to resolve this issue so, when I  tried to check for the issue, I found that when ever so one gets a notification , there's no change in the tray icon , so after looking upon the notification folder , I found out that tray icons must be integrated with the notification folder. This is the possible solution that I can come with.

**Comment by henit-chobisa** [comment]
Hey There, 
This issue is already present in the current version of Rocket Chat ( 3.8.9 ), both `flashframe` and `dockbounce` works if any PM comes to the app.

Kindly update to the latest version & consider closing the issue. 
Thanks! 😊

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
I will be closing this issue because there are duplicated ones.
