### ISSUE TITLE
Images won't display if Rocket.Chat is running behind an nginx reverse proxy

### ISSUE THREAD

**Issue by dkoryavov** [RocketChat/Rocket.Chat.Electron#517]
Hello, 

Our Rocket.Chat installation is running behind nginx reverse proxy.  Config:

    location /rocket {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://[our_rocket_node]/rocket;
  }

With this configuration images just won't display:

![image](https://user-images.githubusercontent.com/7237303/29519101-c7d4324c-8684-11e7-8926-2282d1276efe.png)

But I can see the same image in any web browser. Thus, I believe that this is a problem of the desktop app.

Tested on:
Windows 7 and Ubuntu 16.04 
Rocket.Chat client 2.8.0. 
Rocket.Chat Server 0.58.1.

**Comment by bennlich** [comment]
I'm having the same issue. My rocket chat server is running behind an nginx proxy with `ROOT_URL=https://my.domain/chat/`. Images load correctly on the web client. Surprisingly, the urls it uses are like:
```
/chat/chat/file-upload/nmJDQ5v5BY7BeHjrc/he.png
```
(yes, the double /chat/chat **works**).

Images do not load on the desktop client. It seems to make requests to paths like
```
/chat/file-upload/nmJDQ5v5BY7BeHjrc/he.png
```
which seem more reasonable to me, but do not work.

This issue seems related to https://github.com/RocketChat/Rocket.Chat/issues/2646.

**Comment by bennlich** [comment]
The duplicate path I'm seeing seems related to https://github.com/RocketChat/Rocket.Chat/pull/10029. I'm still stumped about why the duplicate path *works* though, and the non-duplicate path fails.

**Comment by dkoryavov** [comment]
It seems the bug has been fixed in Rocket.Chat 0.63.3, I can see all images. Thus, I close the bug.
