### ISSUE TITLE
Desktop Notifications not working with Rocket.Chat+ 2.8

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat.Electron#522]
@monty241 commented on [Fri Aug 18 2017](https://github.com/RocketChat/Rocket.Chat/issues/7795)

I've configured desktop notifications on Windows 10, Rocket.Chat+ 2.8.0, 1 instance, deployment: snap, db replicaset: ?, node: ?.

The test desktop notifications button works and shows in the bottom right corner a popup.

However, no other notifications appear. Rooms etc all default from account.

Reproduction:

1. Enable in account desktop notifications for messages.
2. Press test. Works.
3. Have someone send something. Nothing appears.

Expectation:

On step 3 a popup appears.

---

@dkoryavov commented on [Thu Aug 24 2017](https://github.com/RocketChat/Rocket.Chat/issues/7795#issuecomment-324571141)

+1
server: Rocket.Chat 0.58.1
client: web or Rocket.Chat.Electron 2.8

Desktop notifications does not work at all . On the previous version (0.57.3) desktop notifications worked fine.

**Comment by alexbrazier** [comment]
@monty241, @dkoryavov Can you check what your notification preferences are in `My Account -> Preferences -> Messages -> Show Desktop Notifications For` or the preference in the admin page

**Comment by dkoryavov** [comment]
I tried to use 'Mentions' and 'All messages'. It does not work anyway (Windows 7 + Rocket.Chat Electron 2.9).

**Comment by monty241** [comment]
See picture. When I press "TEST" (2), (3) appears. Version 2.9.0.
![image](https://user-images.githubusercontent.com/7579444/30266579-275a98bc-96e0-11e7-89e9-224dbe85cf57.png)

**Comment by lcharette** [comment]
I've got the same issue on MacOS, same RC version. 

Note that in my case, the "All messages" notifications doesn't work (no sounds or alert when someone post), but I do get notifications when someone mention me.

**Comment by lcharette** [comment]
FYI, server was updated to 0.59.1 today. Same issue (web or desktop 2.9)

**Comment by lcharette** [comment]
Server was updated to 0.59.1 today. Same issue (web or desktop 2.9)

I found this issue to be related to this setting. Not sure the description is applied correctly ?

![capture d ecran 2017-10-19 a 20 22 59](https://user-images.githubusercontent.com/2566513/31800236-79337758-b50d-11e7-8bc2-22fa51953d71.png)

**Comment by alfredbez** [comment]
I get no notifactions at all.

RC-Server Version: 0.59.3
Client-Version: 2.10.5
My OS: Ubuntu 16.04

The Button "Test Desktop Notifications" does nothing...

**Comment by canove** [comment]
Same here! 

RC-Server Version: 0.59.3
Client-Version: 2.10.5
My OS: Windows 7, Windwos 10.

**Comment by ericjee** [comment]
same issue.
RC-Server Version: 0.64.1
Client-Version: 2.10.5
My OS: macOS 10.13.4

**Comment by adipose** [comment]
No notifications at all in 2.11.0 and Windows 10.

**Comment by sadkins76** [comment]
I have a similar issue.  Windows 10 notifications are ON.  And generally, the notifications work, however, they are not persistent.  Meaning, the notification goes away, and the user, who is not always at their desk, has no idea they have gotten a message until they actually click on the Rocket.Chat window.  On a Mac, using the Rocket.Chat application, the message indicator is shown on the dock icon.  There is NO persistent notification in the Windows version of the application, that I can see or have seen or am aware of.  Is this intentional?  IS there a setting that I am missing?  Our users are completely missing messages because of this.

**Comment by adipose** [comment]
@sadkins76 This is a consequence of using the Windows 10 notification system.  There does not appear to be a way to configure the TTL of a notification in Windows 10 (I checked the settings in the GUI, at least).  The alternatives are to use a custom notification system, or accept that Windows 10 only shows the notifications for ~5 seconds.  But overall, it seems best to use the OS notifications as that's playing nice.  Perhaps a server option to use custom notifications rather than OS ones would be in order?

**Comment by adipose** [comment]
@sadkins76 Huh.  My window already flashes without that setting.  I turned it on and saw no difference in how RocketChat works.

**Comment by sadkins76** [comment]
All of my machines flash for 5 seconds and then stop.  I CAN change that setting to 5 mins, but there are quite a few times where the user will be away from their desk longer than that, so its irrelevant.  We did not have this issue with Pidgin when we used it.  And we don't have this issue with our Mac machines.

**Comment by adipose** [comment]
Mine also flashes for 5 seconds and stops, but it remains highlighted until you click on it.  This is without the audio setting.

**Comment by lukaszbachman** [comment]
We've had similar issues, but it turned out to be improper configuration. I logged in using admin account and went to Administration > Accounts > Default User Preferences.  In my case "Notification Duration" was set to 0, so I changed it to 5. I think that by default desktop notifications only work if you get mentioned by someone in chat window, so you might want to change that too. Please note that each channel might have different notification settings.
As a final note - CTRL+R seemed necessary in case of few of my colleagues for the changes to take effect.

**Comment by tassoevan** [comment]
I'm closing this issue since the original reported bug was fixed.
For issues regarding notification handling in Windows, please follow the discussion at #775.
