### ISSUE TITLE
Chat Notification popup duration

### ISSUE THREAD

**Issue by straytripod** [RocketChat/Rocket.Chat.Electron#555]
I have attempted to change the duration both privately and administratively. The setting does not seem to be working. Is there a configuration file I can set the duration in? 3 seconds pop-up notification is ridiculous.

**Comment by ezef** [comment]
here the same, i set to 0, to never dissapear the notification until the user clicked on it, but not working.

**Comment by Anguel** [comment]
I did some research and it looks like Windows notification duration can be only controlled through Windows registry, i.e. not by applications directly, and can be set only to up to 5 minutes. In order to prevent chat messages from being overlooked (which happens constantly because users not always sitting in front of their PC just don't see the small number in the tray) the only possibility I can think of is to make the Rocket Chat client blink in the **taskbar** (and optionally in the tray), even when minimized to the tray. Blinking the tray only is also not clearly visible.

**Comment by adipose** [comment]
This is a huge problem.  Once in the tray the message is missed 90% of the time.  The icon doesn't even blink or anything, nothing pops up, and having a tiny counter in the corner of the screen doesn't call your attention.

**Comment by Anguel** [comment]
We planned to use RocketChat for internal communication in our small company but now I have completely paused its implementation here until this issue is solved. However nobody at the development team seems to care. For me this is not an enhancement request, it is something that needs an urgent fix! If users don't see the messages the whole thing is useless. I just don't understand how others are using it reliably. Again, please add an option to make the program blink in Windows **task bar** so people can clearly see that there is a new message, or make the program output its own notifications without having to rely on Windows as this is not configurable.

**Comment by arteislt** [comment]
Desktop notification duration (or blinking taskbarsymbol) is a very important feature! If users don't see the messages, they are going to use emails with lots of cc's again :(

**Comment by selimt** [comment]
Hi I did some testing on Linux both with RocketChat desktop client and the notify-send command and when I use notify-send I can get the notifications to stay up indefinitely but with RocketChat even when I put a large value under "Notification Duration" they disappear after 10 minutes. 

Here is the output from dbus-monitor with notify-send:

Command: notify-send --expire-time 0 "test"

dbus-monitor output:

```
method call time=1547745114.237778 sender=:1.1746 -> destination=:1.1740 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method call time=1547745114.238414 sender=:1.1746 -> destination=:1.1740 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "test"
   string ""
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 0
```

Rocket.Chat Desktop, My Account, Notification Duration 9999999, "Test Desktop Notifications" (closes after 10 minutes)

dbus-monitor output:

```
method call time=1547745239.149528 sender=:1.710 -> destination=org.freedesktop.Notifications serial=91 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Rocket.Chat"
   uint32 0
   string "/usr/tmp/tmp-16986vyLS2F6M3A5M.tmp"
   string "Desktop Notification Test"
   string "This is a desktop notification"
   array [
      string "default"
      string ""
   ]
   array [
      dict entry(
         string "urgency"
         variant             int32 2
      )
   ]
   int32 86400000
```

Rocket.Chat Desktop, My Account, Notification Duration 1, "Test Desktop Notifications" (closes after 1 second)

dbus-monitor output:

```
method call time=1547745376.589095 sender=:1.710 -> destination=org.freedesktop.Notifications serial=99 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Rocket.Chat"
   uint32 0
   string "/usr/tmp/tmp-16986vyLS2F6M3A5M.tmp"
   string "Desktop Notification Test"
   string "This is a desktop notification"
   array [
      string "default"
      string ""
   ]
   array [
      dict entry(
         string "urgency"
         variant             int32 2
      )
   ]
   int32 86400000
```

Rocket.Chat Desktop, My Account, Notification Duration 0, "Test Desktop Notifications" (closes after 10 minutes):

```
method call time=1547746366.185498 sender=:1.710 -> destination=org.freedesktop.Notifications serial=105 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Rocket.Chat"
   uint32 0
   string "/usr/tmp/tmp-16986vyLS2F6M3A5M.tmp"
   string "Desktop Notification Test"
   string "This is a desktop notification"
   array [
      string "default"
      string ""
   ]
   array [
      dict entry(
         string "urgency"
         variant             int32 2
      )
   ]
   int32 86400000
```

Note that the last int32 value is always 86400000 no matter what we enter in Rocket Chat settings for the duration while with notify-send the --expire-time seems to correspond to this entry and setting it to 0 allows it to persist indefinitely.

-Selim

**Comment by selimt** [comment]
The other thing I noticed is that with notify-send, the second array has a variant of type byte while the Rocket Chat notifications have a variant of int32. Maybe the signature of the notification doesn't match what dbus expects.

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
I will be closing this issue because there are duplicated ones.
