### ISSUE TITLE
Links with anchors break badly

### ISSUE THREAD

**Issue by reitzig** [RocketChat/Rocket.Chat.Electron#616]
## My Setup
- Operating System: Ubuntu 16.04
- App Version: 2.9.0
- Server Version: 0.57.3

- [ ] I have tested with the latest version
	(Latest version not available as installer/package.)
- [X] I can simulate the issue easily

## Description

Inserting a link with anchor label results in broken HTML in both web and desktop client.

### Current Behavior

I see `#crypto" target="_blank" rel="noopener noreferrer">https://developer.android.com/preview/api-overview.html#crypto`.

![2017-11-27_01](https://user-images.githubusercontent.com/4246780/33257260-d5a5f18a-d355-11e7-8404-ac1692f3e30b.png)

### Expected Behavior
See the equivalent of `[https://developer.android.com/preview/api-overview.html#crypto](https://developer.android.com/preview/api-overview.html#crypto)`.

**Comment by gdelavald** [comment]
Issue moved to [RocketChat/Rocket.Chat #8954](https://github.com/RocketChat/Rocket.Chat/issues/8954) via [**ZenHub**](https://www.zenhub.com/)

**Comment by reitzig** [comment]
@gdelavald Whoops. For future reference, how do I know which repo to report issues in?

**Comment by gdelavald** [comment]
@reitzig Don't worry, the confusion is expected in some cases. Usually anything that can be reproducible in the web version is a problem with the core, so it should be reported in the Rocket.Chat repo.
When the problem is closer to the OS, like native notifications, installation issues, client problems, it's more likely to be a problem with the Electron application, and we can solve it here directly 😄 
Thanks for reporting the issue anyway
