### ISSUE TITLE
Trayicon should blink when a new message arrives a channel (not mentioned) with enabled desktop notifications

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Electron#628]
## My Setup
- Operating System: Windows 10
- App Version: 2.10.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
In https://github.com/RocketChat/Rocket.Chat.Electron/commit/263ee60ce689a1b37ff3239b8e0af6dd477513de @rodrigok make the icon blink if the user is mentioned from another user. We need this functionality also with channels, there the option "Desktop Notification -> All Messages" is set.

Seems like the actual logic to blink is if the icon is displaying a new message (with the ! indicator) -> blink.

### Current Behavior
Icon is blinking if mentioned by another user in a chatroom, icon is not blinking if there is a new message in a chatroom, there the "Desktop Notifications -> All Messages" is set.

### Expected Behavior
The Icon should blink on mentions and new messages in a channel if the option "Desktop Notifications -> All Messages" is set.

**Comment by kiwirot** [comment]
We also would appreciate the feature very much. For the **windows desktop client**, in a channel where the desktop notification is set to **Alerts: All Messages**:

- the notifications work as disired, but
- the icon only blinks for @user mentions (or direct messages)

So it's easy to miss messages from important channels, because the notification just keeps on screen for 5 seconds tops.

**Comment by ankar84** [comment]
@tassoevan 
Our users ask the same as issue starter behavior - icon in task panel (not tray) **should blink on every message** in Desktop Notification preferences is set to **All messages**.

**Comment by jeanfbrito** [comment]
Hello, we will be tracking the blinking icon feature request here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2525
